// Generated by CoffeeScript 1.6.3
(function() {
  Leap.plugin('threejs', function() {
    return {
      frame: function(frame) {
        var finger, hand, _i, _len, _ref, _results;
        _ref = frame.hands;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          hand = _ref[_i];
          hand.fingers = _.sortBy(hand.fingers, function(finger) {
            return finger.id;
          });
          _results.push((function() {
            var _j, _len1, _ref1, _results1;
            _ref1 = hand.fingers;
            _results1 = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              finger = _ref1[_j];
              finger.mcpPosition = (new THREE.Vector3).fromArray(finger.mcpPosition);
              finger.pipPosition = (new THREE.Vector3).fromArray(finger.pipPosition);
              finger.dipPosition = (new THREE.Vector3).fromArray(finger.dipPosition);
              _results1.push(finger.tipPosition = (new THREE.Vector3).fromArray(finger.tipPosition));
            }
            return _results1;
          })());
        }
        return _results;
      }
    };
  });

}).call(this);
