// Generated by CoffeeScript 1.6.3
(function() {
  var HEIGHT, WIDTH, animation, camera, handMesh, pointLight, renderer, scene;

  HEIGHT = window.innerHeight;

  WIDTH = window.innerWidth;

  renderer = new THREE.WebGLRenderer({
    alpha: true
  });

  renderer.setClearColor(0x000000, 1);

  renderer.setSize(WIDTH, HEIGHT);

  document.getElementById('threejs').appendChild(renderer.domElement);

  camera = new THREE.PerspectiveCamera(90, WIDTH / HEIGHT, 10, 1000);

  camera.position.z = 30;

  camera.position.x = 10;

  camera.position.y = 10;

  camera.lookAt(new THREE.Vector3(0, 0, 0));

  scene = new THREE.Scene();

  scene.add(camera);

  scene.add(new THREE.AxisHelper(50));

  scene.add(new THREE.AmbientLight(0x222222));

  pointLight = new THREE.PointLight(0xFFffff);

  pointLight.position = new THREE.Vector3(20, 20, 10);

  pointLight.lookAt(new THREE.Vector3(0, 0, 10));

  scene.add(pointLight);

  animation = void 0;

  handMesh = void 0;

  (new THREE.JSONLoader).load('javascripts/blender-fbx-export.json', function(geometryWithBones, materials) {
    var material;
    material = materials[0];
    THREE.GeometryUtils.center(geometryWithBones);
    handMesh = new THREE.SkinnedMesh(geometryWithBones, material);
    handMesh.scale = new THREE.Vector3(1, 1, 1);
    handMesh.castShadow = true;
    handMesh.receiveShadow = true;
    scene.add(handMesh);
    return renderer.render(scene, camera);
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
